import { execFile } from 'child_process';
import { createHash } from 'crypto';
import { promises as fs } from 'fs';
import * as path from 'path';
import { promisify } from 'util';
import { GeneratedApp, Decision } from '../models/types';

const execFileAsync = promisify(execFile);
const GIT_TIMEOUT_MS = 30_000;
const GH_TIMEOUT_MS = 30_000;

export interface PublishResult {
  repositoryUrl: string;
  branchName: string;
  pullRequestUrl: string;
}

export class GitHubPublisher {
  async saveLocal(app: GeneratedApp, decisions: Decision[], repoPath: string): Promise<PublishResult> {
    const specPath = path.join(repoPath, 'ddd-spec.json');
    const decisionsPath = path.join(repoPath, 'ddd-decisions.json');

    await fs.writeFile(specPath, JSON.stringify(app.spec, null, 2));
    await fs.writeFile(decisionsPath, JSON.stringify(decisions, null, 2));
    await this._writeGeneratedApp(app, decisions, path.join(repoPath, 'generated-app'));

    return {
      repositoryUrl: '',
      branchName: '',
      pullRequestUrl: '',
    };
  }

  async publish(app: GeneratedApp, decisions: Decision[], repoPath: string): Promise<PublishResult> {
    const safeProjectId = this._safeToken(app.projectId);
    const branch = `ddd/${safeProjectId}`;
    const projectDir = path.join(repoPath, app.projectId);
    const specPath = path.join(projectDir, 'ddd-spec.json');
    const decisionsPath = path.join(projectDir, 'ddd-decisions.json');
    const originalBranch = await this._currentBranch(repoPath);

    try {
      try {
        await execFileAsync('git', ['checkout', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      } catch {
        await execFileAsync('git', ['checkout', '-b', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      }

      // Write spec and decisions JSON
      await fs.writeFile(specPath, JSON.stringify(app.spec, null, 2));
      await fs.writeFile(decisionsPath, JSON.stringify(decisions, null, 2));

      await execFileAsync('git', ['add', specPath, decisionsPath], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      const hasStagedChanges = await this._hasStagedChanges(repoPath, [specPath, decisionsPath]);
      if (hasStagedChanges) {
        await execFileAsync('git', ['commit', '-m', 'chore: DDD generated app'], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      }

      try {
        await execFileAsync('git', ['push', '-u', 'origin', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      } catch (err) {
        console.error('DDD: GitHub push failed after local save', err);
        return { repositoryUrl: '', branchName: branch, pullRequestUrl: '' };
      }

      const titleName = typeof app.spec['name'] === 'string' ? app.spec['name'] : app.projectId;
      let stdout: string;
      try {
        ({ stdout } = await execFileAsync(
          'gh',
          [
            'pr',
            'create',
            '--title',
            `DDD: ${titleName}`,
            '--body',
            'Generated by Dopamine Driven Development',
            '--head',
            branch,
          ],
          { cwd: repoPath, timeout: GH_TIMEOUT_MS, shell: false },
        ));
      } catch (err) {
        console.error('DDD: GitHub PR creation failed after local save', err);
        return {
          repositoryUrl: await this._repoUrl(repoPath),
          branchName: branch,
          pullRequestUrl: '',
        };
      }
      const prUrl = stdout.trim();

      return {
        repositoryUrl: await this._repoUrl(repoPath),
        branchName: branch,
        pullRequestUrl: prUrl,
      };
    } catch (err) {
      console.error('DDD: Local publish failed before files were safely saved', err);
      throw err;
    } finally {
      if (originalBranch) {
        try {
          await execFileAsync('git', ['checkout', originalBranch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
        } catch (err) {
          console.error('DDD: Git branch restore failed', err);
        }
      }
    }
  }

  private async _currentBranch(repoPath: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync(
        'git',
        ['rev-parse', '--abbrev-ref', 'HEAD'],
        { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false },
      );
      return stdout.trim();
    } catch (err) {
      console.error('DDD: Git current branch lookup failed', err);
      return '';
    }
  }

  private async _repoUrl(repoPath: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync(
        'gh',
        ['repo', 'view', '--json', 'url', '-q', '.url'],
        { cwd: repoPath, timeout: GH_TIMEOUT_MS, shell: false },
      );
      return stdout.trim();
    } catch (err) {
      console.error('DDD: GitHub repository URL lookup failed', err);
      return '';
    }
  }

  private async _hasStagedChanges(repoPath: string, filePaths: string[]): Promise<boolean> {
    try {
      await execFileAsync(
        'git',
        ['diff', '--cached', '--quiet', '--', ...filePaths],
        { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false },
      );
      return false;
    } catch (err) {
      if (err && typeof err === 'object' && 'code' in err && err.code === 1) {
        return true;
      }
      throw err;
    }
  }

  private _safeToken(value: string): string {
    const sanitized = value.replace(/[^A-Za-z0-9_-]/g, '-');
    if (/[A-Za-z0-9_]/.test(sanitized)) {
      return sanitized;
    }

    const suffix = createHash('sha1').update(value).digest('hex').slice(0, 8);
    return `token-${suffix}`;
  }

  private async _writeGeneratedApp(app: GeneratedApp, decisions: Decision[], appPath: string): Promise<void> {
    await fs.mkdir(path.join(appPath, 'src'), { recursive: true });

    await Promise.all([
      fs.writeFile(path.join(appPath, 'package.json'), this._packageJson(app)),
      fs.writeFile(path.join(appPath, 'index.html'), this._indexHtml(app)),
      fs.writeFile(path.join(appPath, 'src', 'main.js'), this._mainJs(app, decisions)),
      fs.writeFile(path.join(appPath, 'src', 'styles.css'), this._stylesCss()),
      fs.writeFile(path.join(appPath, 'README.md'), this._readme(app)),
    ]);
  }

  private _packageJson(app: GeneratedApp): string {
    const name = this._packageName(this._specString(app.spec, 'name', 'ddd-generated-app'));
    return `${JSON.stringify({
      name,
      version: '0.0.1',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite --host 0.0.0.0',
        build: 'vite build',
        preview: 'vite preview --host 0.0.0.0',
      },
      devDependencies: {
        vite: '^5.4.0',
      },
    }, null, 2)}\n`;
  }

  private _indexHtml(app: GeneratedApp): string {
    const title = this._escapeHtml(this._specString(app.spec, 'name', 'DDD Generated App'));
    return `<!doctype html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;
  }

  private _mainJs(app: GeneratedApp, decisions: Decision[]): string {
    return `import './styles.css';

const appSpec = ${JSON.stringify(app.spec, null, 2)};
const decisions = ${JSON.stringify(decisions, null, 2)};

const asArray = (value) => Array.isArray(value) ? value : [];
const screens = asArray(appSpec.screens);
const features = asArray(appSpec.features);
const acceptedCount = decisions.filter((decision) => decision.action === 'accepted').length;
const rejectedCount = decisions.filter((decision) => decision.action === 'rejected').length;

document.querySelector('#app').innerHTML = \`
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Generated by DDD</p>
      <h1>\${escapeHtml(appSpec.name || 'Generated App')}</h1>
      <p class="summary">\${escapeHtml(appSpec.summary || 'スワイプで選んだ仕様から作成されたアプリです。')}</p>
      <div class="metrics" aria-label="Decision summary">
        <span><strong>\${acceptedCount}</strong> accepted</span>
        <span><strong>\${rejectedCount}</strong> rejected</span>
        <span><strong>\${features.length}</strong> features</span>
      </div>
    </section>

    <section class="workspace">
      <div class="panel primary">
        <div class="section-title">
          <span>Features</span>
          <small>\${features.length} items</small>
        </div>
        <div class="feature-list">
          \${features.length > 0
            ? features.map((feature, index) => \`
              <button class="feature" type="button">
                <span class="feature-index">\${index + 1}</span>
                <span>\${escapeHtml(String(feature))}</span>
              </button>
            \`).join('')
            : '<p class="empty">採用された機能がまだありません。</p>'}
        </div>
      </div>

      <div class="panel">
        <div class="section-title">
          <span>Screens</span>
          <small>\${screens.length} views</small>
        </div>
        <div class="screen-list">
          \${screens.length > 0
            ? screens.map((screen) => \`
              <article class="screen">
                <h2>\${escapeHtml(screen?.name || 'Screen')}</h2>
                <p>\${escapeHtml(screen?.description || '')}</p>
              </article>
            \`).join('')
            : '<p class="empty">画面仕様がまだありません。</p>'}
        </div>
      </div>
    </section>
  </main>
\`;

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
`;
  }

  private _stylesCss(): string {
    return `:root {
  color: #172026;
  background: #f6f8f4;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-width: 320px;
}

button {
  font: inherit;
}

.shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 40px 0;
}

.hero {
  padding: 28px 0 32px;
}

.eyebrow {
  margin: 0 0 10px;
  color: #586a5f;
  font-size: 13px;
  font-weight: 700;
  text-transform: uppercase;
}

h1 {
  margin: 0;
  max-width: 760px;
  color: #121a20;
  font-size: 44px;
  line-height: 1.05;
  letter-spacing: 0;
}

.summary {
  max-width: 720px;
  margin: 18px 0 0;
  color: #40515b;
  font-size: 18px;
  line-height: 1.7;
}

.metrics {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 24px;
}

.metrics span {
  display: inline-flex;
  align-items: baseline;
  gap: 6px;
  min-height: 38px;
  padding: 8px 12px;
  border: 1px solid #d8dfd1;
  border-radius: 8px;
  background: #ffffff;
  color: #55636a;
}

.metrics strong {
  color: #1e6f5c;
  font-size: 20px;
}

.workspace {
  display: grid;
  grid-template-columns: minmax(0, 1.05fr) minmax(320px, 0.95fr);
  gap: 18px;
  align-items: start;
}

.panel {
  border: 1px solid #d9e0d4;
  border-radius: 8px;
  background: #ffffff;
  padding: 18px;
}

.primary {
  background: #fdfefb;
}

.section-title {
  display: flex;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 14px;
  color: #172026;
  font-weight: 800;
}

.section-title small {
  color: #6a7a70;
  font-weight: 600;
}

.feature-list,
.screen-list {
  display: grid;
  gap: 10px;
}

.feature {
  display: grid;
  grid-template-columns: 34px minmax(0, 1fr);
  gap: 12px;
  align-items: center;
  width: 100%;
  min-height: 52px;
  border: 1px solid #dce3d8;
  border-radius: 8px;
  background: #ffffff;
  color: #1d2a30;
  padding: 10px;
  text-align: left;
}

.feature:hover {
  border-color: #77a98b;
  background: #f3faf5;
}

.feature-index {
  display: inline-grid;
  place-items: center;
  width: 34px;
  height: 34px;
  border-radius: 999px;
  background: #1e6f5c;
  color: #ffffff;
  font-size: 13px;
  font-weight: 800;
}

.screen {
  border-left: 4px solid #d78448;
  padding: 10px 12px;
  background: #fbf6ef;
  border-radius: 6px;
}

.screen h2 {
  margin: 0 0 6px;
  font-size: 17px;
  line-height: 1.35;
}

.screen p,
.empty {
  margin: 0;
  color: #52636b;
  line-height: 1.6;
}

@media (max-width: 760px) {
  .shell {
    width: min(100% - 24px, 1120px);
    padding: 24px 0;
  }

  h1 {
    font-size: 34px;
  }

  .summary {
    font-size: 16px;
  }

  .workspace {
    grid-template-columns: 1fr;
  }
}
`;
  }

  private _readme(app: GeneratedApp): string {
    return `# ${this._specString(app.spec, 'name', 'DDD Generated App')}

${this._specString(app.spec, 'summary', 'Generated from ddd-spec.json.')}

## Run

Use the package manager available in your environment.

\`\`\`sh
npm install
npm run dev
\`\`\`

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

\`\`\`sh
yarn install
yarn dev
\`\`\`

\`\`\`sh
bun install
bun run dev
\`\`\`
`;
  }

  private _specString(spec: Record<string, unknown>, key: string, fallback: string): string {
    const value = spec[key];
    return typeof value === 'string' && value.trim() ? value.trim() : fallback;
  }

  private _packageName(value: string): string {
    const name = value.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '');
    return name || 'ddd-generated-app';
  }

  private _escapeHtml(value: string): string {
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }
}
