import { execFile } from 'child_process';
import { promises as fs } from 'fs';
import * as path from 'path';
import { promisify } from 'util';
import { GeneratedApp, Decision } from '../models/types';
import { safePathToken } from './pathUtils';

const execFileAsync = promisify(execFile);
const GIT_TIMEOUT_MS = 30_000;
const GH_TIMEOUT_MS = 30_000;
export const DDD_GENERATED_APPS_DIR = 'ddd-generated-apps';

export interface PublishResult {
  repositoryUrl: string;
  branchName: string;
  pullRequestUrl: string;
}

export class GitHubPublisher {
  async saveLocal(app: GeneratedApp, decisions: Decision[], repoPath: string): Promise<PublishResult> {
    const safeProjectId = safePathToken(app.projectId);
    const projectDir = path.join(repoPath, DDD_GENERATED_APPS_DIR, safeProjectId);
    const specPath = path.join(projectDir, 'ddd-spec.json');
    const decisionsPath = path.join(projectDir, 'ddd-decisions.json');

    await fs.mkdir(projectDir, { recursive: true });
    await fs.writeFile(specPath, JSON.stringify(app.spec, null, 2));
    await fs.writeFile(decisionsPath, JSON.stringify(decisions, null, 2));
    await this._writeGeneratedApp(app, decisions, path.join(projectDir, 'generated-app'));

    return {
      repositoryUrl: '',
      branchName: '',
      pullRequestUrl: '',
    };
  }

  async publish(app: GeneratedApp, decisions: Decision[], repoPath: string): Promise<PublishResult> {
    const safeProjectId = safePathToken(app.projectId);
    const branch = `ddd/${safeProjectId}`;
    const projectDir = path.join(repoPath, DDD_GENERATED_APPS_DIR, safeProjectId);
    const specPath = path.join(projectDir, 'ddd-spec.json');
    const decisionsPath = path.join(projectDir, 'ddd-decisions.json');
    const originalBranch = await this._currentBranch(repoPath);

    try {
      try {
        await execFileAsync('git', ['checkout', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      } catch {
        await execFileAsync('git', ['checkout', '-b', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      }

      await fs.mkdir(projectDir, { recursive: true });
      await fs.writeFile(specPath, JSON.stringify(app.spec, null, 2));
      await fs.writeFile(decisionsPath, JSON.stringify(decisions, null, 2));

      await execFileAsync('git', ['add', specPath, decisionsPath], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      const hasStagedChanges = await this._hasStagedChanges(repoPath, [specPath, decisionsPath]);
      if (hasStagedChanges) {
        await execFileAsync('git', ['commit', '-m', 'chore: DDD generated app'], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      }

      try {
        await execFileAsync('git', ['push', '-u', 'origin', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      } catch (err) {
        console.error('DDD: GitHub push failed after local save', err);
        return { repositoryUrl: '', branchName: branch, pullRequestUrl: '' };
      }

      const titleName = typeof app.spec['name'] === 'string' ? app.spec['name'] : app.projectId;
      let stdout: string;
      try {
        ({ stdout } = await execFileAsync(
          'gh',
          [
            'pr',
            'create',
            '--title',
            `DDD: ${titleName}`,
            '--body',
            'Generated by Dopamine Driven Development',
            '--head',
            branch,
          ],
          { cwd: repoPath, timeout: GH_TIMEOUT_MS, shell: false },
        ));
      } catch (err) {
        console.error('DDD: GitHub PR creation failed after local save', err);
        return {
          repositoryUrl: await this._repoUrl(repoPath),
          branchName: branch,
          pullRequestUrl: '',
        };
      }
      const prUrl = stdout.trim();

      return {
        repositoryUrl: await this._repoUrl(repoPath),
        branchName: branch,
        pullRequestUrl: prUrl,
      };
    } catch (err) {
      console.error('DDD: Local publish failed before files were safely saved', err);
      throw err;
    } finally {
      if (originalBranch) {
        try {
          await execFileAsync('git', ['checkout', originalBranch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
        } catch (err) {
          console.error('DDD: Git branch restore failed', err);
        }
      }
    }
  }

  private async _currentBranch(repoPath: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync(
        'git',
        ['rev-parse', '--abbrev-ref', 'HEAD'],
        { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false },
      );
      return stdout.trim();
    } catch (err) {
      console.error('DDD: Git current branch lookup failed', err);
      return '';
    }
  }

  private async _repoUrl(repoPath: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync(
        'gh',
        ['repo', 'view', '--json', 'url', '-q', '.url'],
        { cwd: repoPath, timeout: GH_TIMEOUT_MS, shell: false },
      );
      return stdout.trim();
    } catch (err) {
      console.error('DDD: GitHub repository URL lookup failed', err);
      return '';
    }
  }

  private async _hasStagedChanges(repoPath: string, filePaths: string[]): Promise<boolean> {
    try {
      await execFileAsync(
        'git',
        ['diff', '--cached', '--quiet', '--', ...filePaths],
        { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false },
      );
      return false;
    } catch (err) {
      if (err && typeof err === 'object' && 'code' in err && err.code === 1) {
        return true;
      }
      throw err;
    }
  }

  private async _writeGeneratedApp(app: GeneratedApp, decisions: Decision[], appPath: string): Promise<void> {
    await fs.mkdir(path.join(appPath, 'src'), { recursive: true });

    await Promise.all([
      fs.writeFile(path.join(appPath, 'package.json'), this._packageJson(app)),
      fs.writeFile(path.join(appPath, 'index.html'), this._indexHtml(app)),
      fs.writeFile(path.join(appPath, 'src', 'main.js'), this._mainJs(app, decisions)),
      fs.writeFile(path.join(appPath, 'src', 'styles.css'), this._stylesCss()),
      fs.writeFile(path.join(appPath, 'README.md'), this._readme(app)),
    ]);
  }

  private _packageJson(app: GeneratedApp): string {
    const name = this._packageName(this._specString(app.spec, 'name', 'ddd-generated-app'));
    return `${JSON.stringify({
      name,
      version: '0.0.1',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite --host 0.0.0.0',
        build: 'vite build',
        preview: 'vite preview --host 0.0.0.0',
      },
      devDependencies: {
        vite: '^8.0.14',
      },
    }, null, 2)}\n`;
  }

  private _indexHtml(app: GeneratedApp): string {
    const title = this._escapeHtml(this._specString(app.spec, 'name', 'DDD Generated App'));
    return `<!doctype html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${title}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;
  }

  private _mainJs(app: GeneratedApp, _decisions: Decision[]): string {
    return `import './styles.css';
import appSpec from '../../ddd-spec.json';

const asArray = (value) => Array.isArray(value) ? value : [];
const features = asArray(appSpec.features);
const screens = asArray(appSpec.screens);
const blueprint = appSpec.blueprint && typeof appSpec.blueprint === 'object' ? appSpec.blueprint : null;
const appText = [appSpec.name, appSpec.summary, ...features].join(' ').toLowerCase();
const isHabitApp = /habit|習慣|継続|チェックイン|連続達成/.test(appText);
const isTodoApp = !isHabitApp && /todo|to-do|タスク|todoリスト|チェック/.test(appText);
const storageKey = \`ddd-generated:\${appSpec.name || 'app'}\`;
const todayIso = () => new Date().toISOString().slice(0, 10);

function loadState(key, fallback) {
  try {
    const raw = localStorage.getItem(\`\${storageKey}:\${key}\`);
    return raw ? { ...fallback, ...JSON.parse(raw) } : fallback;
  } catch {
    return fallback;
  }
}

function saveState(key, value) {
  try {
    localStorage.setItem(\`\${storageKey}:\${key}\`, JSON.stringify(value));
  } catch {
    // localStorage may be unavailable in restricted previews.
  }
}

const todoState = loadState('todo', {
  draft: '',
  dueDate: todayIso(),
  editingId: null,
  editingTitle: '',
  tasks: [
    { id: 1, title: '企画メモを整理する', dueDate: todayIso(), done: false },
    { id: 2, title: '今日の優先タスクを決める', dueDate: '', done: false },
  ],
});

const habitState = loadState('habit', {
  draftName: '',
  draftTarget: 1,
  draftPattern: '毎日',
  habits: [
    { id: 1, name: '朝のストレッチ', target: 1, count: 0, streak: 3, pattern: '毎日', memo: '5分で開始' },
    { id: 2, name: '英単語レビュー', target: 3, count: 1, streak: 5, pattern: '平日だけ', memo: '短く継続' },
  ],
});

const genericState = loadState('generic', {
  activeScreen: 0,
  draftTitle: '',
  draftNote: '',
  entries: [
    { id: 1, title: '最初の項目', note: 'ここから内容を追加・更新できます。', status: 'active' },
  ],
});

const nextTaskId = () => Math.max(0, ...todoState.tasks.map((task) => task.id)) + 1;
const nextHabitId = () => Math.max(0, ...habitState.habits.map((habit) => habit.id)) + 1;
const nextEntryId = () => Math.max(0, ...genericState.entries.map((entry) => entry.id)) + 1;

const blueprintFields = blueprint ? asArray(blueprint.fields).filter((field) => field && typeof field === 'object') : [];
const blueprintStatuses = blueprint ? asArray(blueprint.statuses).map(String).filter(Boolean) : [];
const blueprintSeedItems = blueprint ? asArray(blueprint.seedItems).filter((item) => item && typeof item === 'object') : [];
const blueprintState = loadState('blueprint', {
  draft: Object.fromEntries(blueprintFields.map((field) => [safeFieldKey(field), defaultFieldValue(field)])),
  items: blueprintSeedItems.map((item, index) => ({
    id: index + 1,
    status: blueprintStatuses[0] || 'active',
    values: coerceBlueprintValues(item),
  })),
});
const nextBlueprintId = () => Math.max(0, ...blueprintState.items.map((item) => item.id)) + 1;

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function formatDate(value) {
  if (!value) return '期限なし';
  const date = new Date(\`\${value}T00:00:00\`);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('ja-JP', { month: 'short', day: 'numeric' });
}

function dueStatus(task) {
  if (!task.dueDate || task.done) return '';
  const today = todayIso();
  if (task.dueDate < today) return 'overdue';
  if (task.dueDate === today) return 'today';
  return 'upcoming';
}

function sortTasks(tasks) {
  return [...tasks].sort((a, b) => {
    if (a.done !== b.done) return a.done ? 1 : -1;
    const aDue = a.dueDate || '9999-12-31';
    const bDue = b.dueDate || '9999-12-31';
    return aDue.localeCompare(bDue) || a.id - b.id;
  });
}

function render() {
  if (blueprint && blueprintFields.length > 0) {
    renderBlueprintApp();
    return;
  }

  if (isHabitApp) {
    renderHabitApp();
    return;
  }

  if (isTodoApp) {
    renderTodoApp();
    return;
  }

  renderGenericApp();
}

function safeFieldKey(field) {
  const key = String(field.key || field.label || '').replace(/[^a-zA-Z0-9_-]/g, '').trim();
  return key || 'value';
}

function fieldLabel(field) {
  return String(field.label || field.key || '項目');
}

function fieldType(field) {
  const type = String(field.type || 'text');
  return ['text', 'number', 'date', 'select', 'checkbox'].includes(type) ? type : 'text';
}

function defaultFieldValue(field) {
  const type = fieldType(field);
  if (type === 'checkbox') return false;
  if (type === 'number') return 0;
  if (type === 'date') return todayIso();
  const options = asArray(field.options);
  if (type === 'select' && options.length > 0) return String(options[0]);
  return '';
}

function coerceBlueprintValues(source) {
  return Object.fromEntries(blueprintFields.map((field) => {
    const key = safeFieldKey(field);
    const value = source[key] ?? source[field.label] ?? defaultFieldValue(field);
    return [key, fieldType(field) === 'checkbox' ? Boolean(value) : value];
  }));
}

function renderFieldInput(field, value, prefix = 'blueprint-field') {
  const key = safeFieldKey(field);
  const label = escapeHtml(fieldLabel(field));
  const type = fieldType(field);
  const placeholder = escapeHtml(String(field.placeholder || ''));
  if (type === 'select') {
    const options = asArray(field.options).map(String);
    return \`
      <label>
        <span>\${label}</span>
        <select data-field="\${escapeHtml(key)}" class="\${prefix}">
          \${options.map((option) => \`<option value="\${escapeHtml(option)}" \${String(value) === option ? 'selected' : ''}>\${escapeHtml(option)}</option>\`).join('')}
        </select>
      </label>
    \`;
  }
  if (type === 'checkbox') {
    return \`
      <label class="inline-check">
        <input data-field="\${escapeHtml(key)}" class="\${prefix}" type="checkbox" \${value ? 'checked' : ''} />
        <span>\${label}</span>
      </label>
    \`;
  }
  return \`
    <label>
      <span>\${label}</span>
      <input data-field="\${escapeHtml(key)}" class="\${prefix}" type="\${type}" value="\${escapeHtml(String(value ?? ''))}" placeholder="\${placeholder}" />
    </label>
  \`;
}

function renderBlueprintApp() {
  const entityName = String(blueprint.entityName || appSpec.name || '項目');
  const itemName = String(blueprint.itemName || entityName);
  const statuses = blueprintStatuses.length > 0 ? blueprintStatuses : ['active', 'done'];
  const done = blueprintState.items.filter((item) => item.status === statuses[statuses.length - 1]).length;

  document.querySelector('#app').innerHTML = \`
    <main class="shell">
      <section class="hero">
        <p class="eyebrow">Generated by DDD</p>
        <h1>\${escapeHtml(appSpec.name || entityName)}</h1>
        <p class="summary">\${escapeHtml(appSpec.summary || \`\${entityName}を追加して状態を管理できます。\`)}</p>
        <div class="metrics" aria-label="Blueprint summary">
          <span><strong>\${blueprintState.items.length}</strong> \${escapeHtml(itemName)}</span>
          <span><strong>\${done}</strong> done</span>
          <span><strong>\${blueprintFields.length}</strong> fields</span>
        </div>
      </section>

      <section class="workspace blueprint-workspace">
        <form class="todo-form blueprint-form" id="blueprint-form">
          \${blueprintFields.map((field) => renderFieldInput(field, blueprintState.draft[safeFieldKey(field)])).join('')}
          <button class="primary-action" type="submit">\${escapeHtml(String(blueprint.primaryActionLabel || '追加'))}</button>
        </form>

        <div class="todo-list" aria-label="\${escapeHtml(entityName)}一覧">
          \${blueprintState.items.length > 0
            ? blueprintState.items.map((item) => renderBlueprintItem(item, statuses)).join('')
            : \`<p class="empty">\${escapeHtml(String(blueprint.emptyMessage || \`\${itemName}を追加するとここに表示されます。\`))}</p>\`}
        </div>

        <aside class="requirements-note">
          <h2>反映した機能要件</h2>
          <ul class="requirements">
            \${features.map((feature) => \`<li>\${escapeHtml(feature)}</li>\`).join('')}
          </ul>
        </aside>
      </section>
    </main>
  \`;

  document.querySelectorAll('.blueprint-field').forEach((input) => {
    input.addEventListener('input', () => {
      blueprintState.draft[input.dataset.field] = input.type === 'checkbox' ? input.checked : input.value;
      saveState('blueprint', blueprintState);
    });
    input.addEventListener('change', () => {
      blueprintState.draft[input.dataset.field] = input.type === 'checkbox' ? input.checked : input.value;
      saveState('blueprint', blueprintState);
    });
  });

  document.querySelector('#blueprint-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const values = { ...blueprintState.draft };
    const requiredField = blueprintFields.find((field) => field.required && !String(values[safeFieldKey(field)] ?? '').trim());
    if (requiredField) {
      document.querySelector(\`.blueprint-field[data-field="\${safeFieldKey(requiredField)}"]\`)?.focus();
      return;
    }
    blueprintState.items.push({
      id: nextBlueprintId(),
      status: statuses[0],
      values,
    });
    blueprintState.draft = Object.fromEntries(blueprintFields.map((field) => [safeFieldKey(field), defaultFieldValue(field)]));
    saveState('blueprint', blueprintState);
    render();
  });

  document.querySelectorAll('[data-blueprint-cycle]').forEach((button) => {
    button.addEventListener('click', () => {
      const item = blueprintState.items.find((candidate) => candidate.id === Number(button.dataset.blueprintCycle));
      if (!item) return;
      const currentIndex = Math.max(0, statuses.indexOf(item.status));
      item.status = statuses[(currentIndex + 1) % statuses.length];
      saveState('blueprint', blueprintState);
      render();
    });
  });

  document.querySelectorAll('[data-blueprint-delete]').forEach((button) => {
    button.addEventListener('click', () => {
      blueprintState.items = blueprintState.items.filter((item) => item.id !== Number(button.dataset.blueprintDelete));
      saveState('blueprint', blueprintState);
      render();
    });
  });
}

function renderBlueprintItem(item, statuses) {
  const primaryField = blueprintFields.find((field) => ['text', 'select'].includes(fieldType(field))) || blueprintFields[0];
  const primaryKey = safeFieldKey(primaryField);
  const title = item.values[primaryKey] || \`\${blueprint.itemName || '項目'} \${item.id}\`;
  const detailFields = blueprintFields.filter((field) => safeFieldKey(field) !== primaryKey);
  const doneStatus = statuses[statuses.length - 1];
  return \`
    <article class="todo-item \${item.status === doneStatus ? 'done' : ''}">
      <div class="status-dot \${escapeHtml(item.status)}"></div>
      <div class="todo-copy">
        <strong class="entry-title">\${escapeHtml(String(title))}</strong>
        <div class="todo-meta">
          \${detailFields.map((field) => {
            const key = safeFieldKey(field);
            const value = fieldType(field) === 'checkbox'
              ? (item.values[key] ? 'はい' : 'いいえ')
              : (item.values[key] || '未設定');
            return \`<span>\${escapeHtml(fieldLabel(field))}: \${escapeHtml(String(value))}</span>\`;
          }).join('')}
          <strong>\${escapeHtml(statusLabel(item.status))}</strong>
        </div>
      </div>
      <div class="todo-actions">
        <button class="ghost-action" type="button" data-blueprint-cycle="\${item.id}">\${escapeHtml(String(blueprint.secondaryActionLabel || '状態変更'))}</button>
        <button class="danger-action" type="button" data-blueprint-delete="\${item.id}">削除</button>
      </div>
    </article>
  \`;
}

function statusLabel(value) {
  const labels = { active: '進行中', review: '確認中', done: '完了', pending: '未完了' };
  return labels[value] || value;
}

function renderGenericApp() {
  const activeScreen = screens[genericState.activeScreen] || screens[0];
  const done = genericState.entries.filter((entry) => entry.status === 'done').length;
  document.querySelector('#app').innerHTML = \`
    <main class="shell">
      <section class="hero">
        <p class="eyebrow">Generated by DDD</p>
        <h1>\${escapeHtml(appSpec.name || 'Generated App')}</h1>
        <p class="summary">\${escapeHtml(appSpec.summary || '選んだ機能を操作できるミニアプリです。')}</p>
        <div class="metrics" aria-label="Workspace summary">
          <span><strong>\${genericState.entries.length}</strong> items</span>
          <span><strong>\${done}</strong> done</span>
          <span><strong>\${features.length}</strong> features</span>
        </div>
      </section>

      <section class="workspace generic-workspace">
        \${screens.length > 0
          ? \`<nav class="app-tabs" aria-label="Screens">
              \${screens.map((screen, index) => \`
                <button class="\${genericState.activeScreen === index ? 'active' : ''}" type="button" data-screen="\${index}">
                  \${escapeHtml(screen.name || \`画面\${index + 1}\`)}
                </button>
              \`).join('')}
            </nav>\`
          : ''}

        <article class="panel">
          <h2>\${escapeHtml(activeScreen?.name || 'ワークスペース')}</h2>
          <p>\${escapeHtml(activeScreen?.description || '項目を追加し、状態を進めながら使えるワークスペースです。')}</p>
        </article>

        <form class="todo-form" id="generic-form">
          <label>
            <span>名前</span>
            <input id="generic-title" type="text" value="\${escapeHtml(genericState.draftTitle)}" placeholder="新しい項目" />
          </label>
          <label>
            <span>メモ</span>
            <input id="generic-note" type="text" value="\${escapeHtml(genericState.draftNote)}" placeholder="補足や状態" />
          </label>
          <button class="primary-action" type="submit">追加</button>
        </form>

        <div class="todo-list" aria-label="項目一覧">
          \${genericState.entries.map((entry) => \`
            <article class="todo-item \${entry.status === 'done' ? 'done' : ''}">
              <div class="status-dot \${entry.status}"></div>
              <div class="todo-copy">
                <strong class="entry-title">\${escapeHtml(entry.title)}</strong>
                <div class="todo-meta">
                  <span>\${escapeHtml(entry.note || 'メモなし')}</span>
                  <strong>\${entry.status === 'done' ? '完了' : entry.status === 'review' ? '確認中' : '進行中'}</strong>
                </div>
              </div>
              <div class="todo-actions">
                <button class="ghost-action" type="button" data-cycle="\${entry.id}">状態変更</button>
                <button class="danger-action" type="button" data-delete-entry="\${entry.id}">削除</button>
              </div>
            </article>
          \`).join('')}
        </div>

        <aside class="requirements-note">
          <h2>反映した機能要件</h2>
          <ul class="requirements">
            \${features.map((feature) => \`<li>\${escapeHtml(feature)}</li>\`).join('')}
          </ul>
        </aside>
      </section>
    </main>
  \`;

  document.querySelectorAll('[data-screen]').forEach((button) => {
    button.addEventListener('click', () => {
      genericState.activeScreen = Number(button.dataset.screen);
      saveState('generic', genericState);
      render();
    });
  });

  document.querySelector('#generic-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const titleInput = document.querySelector('#generic-title');
    const noteInput = document.querySelector('#generic-note');
    const title = titleInput.value.trim();
    if (!title) {
      titleInput.focus();
      return;
    }
    genericState.entries.push({
      id: nextEntryId(),
      title,
      note: noteInput.value.trim(),
      status: 'active',
    });
    genericState.draftTitle = '';
    genericState.draftNote = '';
    saveState('generic', genericState);
    render();
  });

  document.querySelector('#generic-title')?.addEventListener('input', (event) => {
    genericState.draftTitle = event.target.value;
    saveState('generic', genericState);
  });

  document.querySelector('#generic-note')?.addEventListener('input', (event) => {
    genericState.draftNote = event.target.value;
    saveState('generic', genericState);
  });

  document.querySelectorAll('[data-cycle]').forEach((button) => {
    button.addEventListener('click', () => {
      const entry = genericState.entries.find((candidate) => candidate.id === Number(button.dataset.cycle));
      if (!entry) return;
      entry.status = entry.status === 'active' ? 'review' : entry.status === 'review' ? 'done' : 'active';
      saveState('generic', genericState);
      render();
    });
  });

  document.querySelectorAll('[data-delete-entry]').forEach((button) => {
    button.addEventListener('click', () => {
      genericState.entries = genericState.entries.filter((entry) => entry.id !== Number(button.dataset.deleteEntry));
      saveState('generic', genericState);
      render();
    });
  });
}

function renderHabitApp() {
  const completed = habitState.habits.filter((habit) => habit.count >= habit.target).length;
  const totalCount = habitState.habits.reduce((sum, habit) => sum + habit.count, 0);

  document.querySelector('#app').innerHTML = \`
    <main class="shell">
      <section class="hero">
        <p class="eyebrow">Generated by DDD</p>
        <h1>\${escapeHtml(appSpec.name || '習慣トラッカー')}</h1>
        <p class="summary">\${escapeHtml(appSpec.summary || '習慣を登録し、今日の達成状況と継続日数を管理できます。')}</p>
        <div class="metrics" aria-label="Habit summary">
          <span><strong>\${completed}</strong> complete</span>
          <span><strong>\${totalCount}</strong> checks</span>
          <span><strong>\${habitState.habits.length}</strong> habits</span>
        </div>
      </section>

      <section class="workspace habit-workspace">
        <form class="todo-form" id="habit-form">
          <label>
            <span>習慣名</span>
            <input id="habit-name" type="text" value="\${escapeHtml(habitState.draftName)}" placeholder="例: 水を飲む" />
          </label>
          <label>
            <span>目標回数</span>
            <input id="habit-target" type="number" min="1" value="\${escapeHtml(habitState.draftTarget)}" />
          </label>
          <label>
            <span>パターン</span>
            <select id="habit-pattern">
              \${['毎日', '平日だけ', '週3回', '曜日を選ぶ'].map((pattern) => \`
                <option value="\${pattern}" \${habitState.draftPattern === pattern ? 'selected' : ''}>\${pattern}</option>
              \`).join('')}
            </select>
          </label>
          <button class="primary-action" type="submit">保存</button>
        </form>

        <div class="habit-grid" aria-label="今日の習慣">
          \${habitState.habits.map((habit) => {
            const complete = habit.count >= habit.target;
            return \`
              <article class="habit-card \${complete ? 'complete' : ''}">
                <div>
                  <h2>\${escapeHtml(habit.name)}</h2>
                  <p>\${escapeHtml(habit.memo || habit.pattern)}</p>
                </div>
                <div class="habit-progress">
                  <strong>\${habit.count}</strong>
                  <span>/ \${habit.target}</span>
                </div>
                <div class="habit-actions">
                  <button class="ghost-action" type="button" data-decrement="\${habit.id}">-</button>
                  <button class="primary-action" type="button" data-increment="\${habit.id}">記録</button>
                  <button class="danger-action" type="button" data-delete-habit="\${habit.id}">削除</button>
                </div>
                <div class="todo-meta">
                  <span>\${escapeHtml(habit.pattern)}</span>
                  <strong>\${complete ? '今日達成' : \`あと\${habit.target - habit.count}回\`}</strong>
                  <span>連続 \${habit.streak} 日</span>
                </div>
              </article>
            \`;
          }).join('')}
        </div>

        <aside class="requirements-note">
          <h2>反映した機能要件</h2>
          <ul class="requirements">
            \${features.map((feature) => \`<li>\${escapeHtml(feature)}</li>\`).join('')}
          </ul>
        </aside>
      </section>
    </main>
  \`;

  document.querySelector('#habit-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const nameInput = document.querySelector('#habit-name');
    const targetInput = document.querySelector('#habit-target');
    const patternInput = document.querySelector('#habit-pattern');
    const name = nameInput.value.trim();
    if (!name) {
      nameInput.focus();
      return;
    }
    habitState.habits.push({
      id: nextHabitId(),
      name,
      target: Math.max(1, Number(targetInput.value) || 1),
      count: 0,
      streak: 0,
      pattern: patternInput.value,
      memo: '',
    });
    habitState.draftName = '';
    habitState.draftTarget = Math.max(1, Number(targetInput.value) || 1);
    habitState.draftPattern = patternInput.value;
    saveState('habit', habitState);
    render();
  });

  document.querySelector('#habit-name')?.addEventListener('input', (event) => {
    habitState.draftName = event.target.value;
    saveState('habit', habitState);
  });

  document.querySelector('#habit-target')?.addEventListener('input', (event) => {
    habitState.draftTarget = Math.max(1, Number(event.target.value) || 1);
    saveState('habit', habitState);
  });

  document.querySelector('#habit-pattern')?.addEventListener('change', (event) => {
    habitState.draftPattern = event.target.value;
    saveState('habit', habitState);
  });

  document.querySelectorAll('[data-increment]').forEach((button) => {
    button.addEventListener('click', () => {
      const habit = habitState.habits.find((candidate) => candidate.id === Number(button.dataset.increment));
      if (!habit) return;
      const wasIncomplete = habit.count < habit.target;
      habit.count = Math.min(habit.target, habit.count + 1);
      if (wasIncomplete && habit.count >= habit.target) habit.streak += 1;
      saveState('habit', habitState);
      render();
    });
  });

  document.querySelectorAll('[data-decrement]').forEach((button) => {
    button.addEventListener('click', () => {
      const habit = habitState.habits.find((candidate) => candidate.id === Number(button.dataset.decrement));
      if (!habit) return;
      const wasComplete = habit.count >= habit.target;
      habit.count = Math.max(0, habit.count - 1);
      if (wasComplete && habit.count < habit.target) habit.streak = Math.max(0, habit.streak - 1);
      saveState('habit', habitState);
      render();
    });
  });

  document.querySelectorAll('[data-delete-habit]').forEach((button) => {
    button.addEventListener('click', () => {
      habitState.habits = habitState.habits.filter((habit) => habit.id !== Number(button.dataset.deleteHabit));
      saveState('habit', habitState);
      render();
    });
  });
}

function renderTodoApp() {
  const sortedTasks = sortTasks(todoState.tasks);
  const completed = todoState.tasks.filter((task) => task.done).length;
  const active = todoState.tasks.length - completed;

  document.querySelector('#app').innerHTML = \`
    <main class="shell">
      <section class="hero">
        <p class="eyebrow">Generated by DDD</p>
        <h1>\${escapeHtml(appSpec.name || 'Todo App')}</h1>
        <p class="summary">\${escapeHtml(appSpec.summary || 'タスクを追加し、期限と完了状態を管理できます。')}</p>
        <div class="metrics" aria-label="Todo summary">
          <span><strong>\${active}</strong> active</span>
          <span><strong>\${completed}</strong> done</span>
          <span><strong>\${todoState.tasks.length}</strong> total</span>
        </div>
      </section>

      <section class="workspace todo-workspace">
        <form class="todo-form" id="todo-form">
          <label>
            <span>タスク名</span>
            <input id="todo-title" type="text" value="\${escapeHtml(todoState.draft)}" placeholder="例: ワイヤーフレームを作る" />
          </label>
          <label>
            <span>期限</span>
            <input id="todo-due" type="date" value="\${escapeHtml(todoState.dueDate)}" />
          </label>
          <button class="primary-action" type="submit">追加</button>
        </form>

        <div class="todo-list" aria-label="タスク一覧">
          \${sortedTasks.length > 0
            ? sortedTasks.map((task) => {
              const status = dueStatus(task);
              const isEditing = todoState.editingId === task.id;
              return \`
                <article class="todo-item \${task.done ? 'done' : ''} \${status}" data-id="\${task.id}">
                  <label class="check-row">
                    <input class="toggle-task" type="checkbox" data-id="\${task.id}" \${task.done ? 'checked' : ''} />
                    <span class="fake-check"></span>
                  </label>
                  <div class="todo-copy">
                    \${isEditing
                      ? \`<input class="edit-input" data-id="\${task.id}" value="\${escapeHtml(todoState.editingTitle)}" />\`
                      : \`<button class="title-button" type="button" data-edit="\${task.id}">\${escapeHtml(task.title)}</button>\`}
                    <div class="todo-meta">
                      <span>\${escapeHtml(formatDate(task.dueDate))}</span>
                      \${status === 'today' ? '<strong>今日が期限</strong>' : ''}
                      \${status === 'overdue' ? '<strong>期限切れ</strong>' : ''}
                      \${status === 'upcoming' ? '<strong>期限あり</strong>' : ''}
                    </div>
                  </div>
                  <div class="todo-actions">
                    \${isEditing
                      ? \`<button class="ghost-action" type="button" data-save="\${task.id}">保存</button>\`
                      : \`<button class="ghost-action" type="button" data-edit="\${task.id}">編集</button>\`}
                    <button class="danger-action" type="button" data-delete="\${task.id}">削除</button>
                  </div>
                </article>
              \`;
            }).join('')
            : '<p class="empty">タスクを追加するとここに表示されます。</p>'}
        </div>

        <aside class="requirements-note">
          <h2>反映した機能要件</h2>
          <ul class="requirements">
            \${features.map((feature) => \`<li>\${escapeHtml(feature)}</li>\`).join('')}
          </ul>
        </aside>
      </section>
    </main>
  \`;

  document.querySelector('#todo-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const titleInput = document.querySelector('#todo-title');
    const dueInput = document.querySelector('#todo-due');
    const title = titleInput.value.trim();
    if (!title) {
      titleInput.focus();
      return;
    }
    todoState.tasks.push({
      id: nextTaskId(),
      title,
      dueDate: dueInput.value,
      done: false,
    });
    todoState.draft = '';
    todoState.dueDate = dueInput.value || todayIso();
    saveState('todo', todoState);
    render();
  });

  document.querySelector('#todo-title')?.addEventListener('input', (event) => {
    todoState.draft = event.target.value;
    saveState('todo', todoState);
  });

  document.querySelector('#todo-due')?.addEventListener('input', (event) => {
    todoState.dueDate = event.target.value;
    saveState('todo', todoState);
  });

  document.querySelectorAll('.toggle-task').forEach((input) => {
    input.addEventListener('change', () => {
      const task = todoState.tasks.find((candidate) => candidate.id === Number(input.dataset.id));
      if (task) {
        task.done = input.checked;
        saveState('todo', todoState);
        render();
      }
    });
  });

  document.querySelectorAll('[data-edit]').forEach((button) => {
    button.addEventListener('click', () => {
      const task = todoState.tasks.find((candidate) => candidate.id === Number(button.dataset.edit));
      if (!task) return;
      todoState.editingId = task.id;
      todoState.editingTitle = task.title;
      saveState('todo', todoState);
      render();
      document.querySelector(\`.edit-input[data-id="\${task.id}"]\`)?.focus();
    });
  });

  document.querySelectorAll('.edit-input').forEach((input) => {
    input.addEventListener('input', () => {
      todoState.editingTitle = input.value;
      saveState('todo', todoState);
    });
    input.addEventListener('keydown', (event) => {
      if (event.key === 'Enter') saveEdit(Number(input.dataset.id));
      if (event.key === 'Escape') {
        todoState.editingId = null;
        todoState.editingTitle = '';
        saveState('todo', todoState);
        render();
      }
    });
  });

  document.querySelectorAll('[data-save]').forEach((button) => {
    button.addEventListener('click', () => saveEdit(Number(button.dataset.save)));
  });

  document.querySelectorAll('[data-delete]').forEach((button) => {
    button.addEventListener('click', () => {
      todoState.tasks = todoState.tasks.filter((task) => task.id !== Number(button.dataset.delete));
      saveState('todo', todoState);
      render();
    });
  });
}

function saveEdit(id) {
  const task = todoState.tasks.find((candidate) => candidate.id === id);
  const title = todoState.editingTitle.trim();
  if (task && title) {
    task.title = title;
  }
  todoState.editingId = null;
  todoState.editingTitle = '';
  saveState('todo', todoState);
  render();
}

render();
`;
  }

  private _stylesCss(): string {
    return `:root {
  color: #172026;
  background: #f6f8f4;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-width: 320px;
}

button {
  font: inherit;
}

.shell {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 40px 0;
}

.hero {
  padding: 28px 0 32px;
}

.eyebrow {
  margin: 0 0 10px;
  color: #586a5f;
  font-size: 13px;
  font-weight: 700;
  text-transform: uppercase;
}

h1 {
  margin: 0;
  max-width: 760px;
  color: #121a20;
  font-size: 44px;
  line-height: 1.05;
  letter-spacing: 0;
}

.summary {
  max-width: 720px;
  margin: 18px 0 0;
  color: #40515b;
  font-size: 18px;
  line-height: 1.7;
}

.metrics {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  margin-top: 24px;
}

.metrics span {
  display: inline-flex;
  align-items: baseline;
  gap: 6px;
  min-height: 38px;
  padding: 8px 12px;
  border: 1px solid #d8dfd1;
  border-radius: 8px;
  background: #ffffff;
  color: #55636a;
}

.metrics strong {
  color: #1e6f5c;
  font-size: 20px;
}

.workspace {
  display: grid;
  gap: 12px;
}

.panel,
.todo-form,
.todo-item,
.habit-card,
.requirements-note {
  border: 1px solid #dce3d8;
  border-radius: 8px;
  background: #ffffff;
  box-shadow: 0 1px 0 rgba(18, 26, 32, 0.03);
}

.panel,
.requirements-note {
  padding: 18px;
}

.panel h2,
.requirements-note h2 {
  margin: 0 0 8px;
  font-size: 17px;
}

.panel p,
.requirements-note p {
  margin: 0;
  color: #52636b;
  line-height: 1.6;
}

.requirements {
  display: grid;
  gap: 8px;
  margin: 14px 0 0;
  padding-left: 18px;
  color: #40515b;
  line-height: 1.5;
}

.app-tabs {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.app-tabs button {
  border: 1px solid #d8dfd1;
  border-radius: 999px;
  background: #ffffff;
  color: #52636b;
  padding: 8px 12px;
  font-weight: 800;
}

.app-tabs button.active {
  border-color: #1e6f5c;
  background: #edf8f2;
  color: #1e6f5c;
}

.todo-workspace {
  gap: 14px;
}

.todo-form {
  display: grid;
  grid-template-columns: minmax(220px, 1fr) 180px auto;
  gap: 12px;
  align-items: end;
  padding: 14px;
}

.todo-form label {
  display: grid;
  gap: 6px;
  color: #52636b;
  font-size: 12px;
  font-weight: 700;
}

.todo-form input,
.todo-form select,
.edit-input {
  width: 100%;
  min-height: 44px;
  border: 1px solid #cfdbd2;
  border-radius: 8px;
  background: #fbfdf9;
  color: #172026;
  padding: 10px 12px;
  font: inherit;
}

.status-dot {
  width: 14px;
  height: 14px;
  border-radius: 50%;
  background: #94a3b8;
}

.status-dot.review {
  background: #d97706;
}

.status-dot.done {
  background: #1e6f5c;
}

.primary-action,
.ghost-action,
.danger-action,
.title-button {
  border: 0;
  border-radius: 8px;
  cursor: pointer;
}

.primary-action {
  min-height: 44px;
  background: #1e6f5c;
  color: #ffffff;
  padding: 0 20px;
  font-weight: 800;
}

.todo-list {
  display: grid;
  gap: 10px;
}

.todo-item {
  display: grid;
  grid-template-columns: auto minmax(0, 1fr) auto;
  gap: 12px;
  align-items: center;
  min-height: 76px;
  padding: 14px;
}

.todo-item.today {
  border-color: #1e6f5c;
  background: #f3faf5;
}

.todo-item.overdue {
  border-color: #d97706;
  background: #fff7ed;
}

.todo-item.done {
  opacity: 0.72;
}

.todo-item.done .title-button {
  text-decoration: line-through;
}

.check-row {
  display: grid;
  place-items: center;
}

.toggle-task {
  width: 22px;
  height: 22px;
  accent-color: #1e6f5c;
}

.todo-copy {
  min-width: 0;
}

.title-button {
  display: block;
  max-width: 100%;
  background: transparent;
  color: #172026;
  padding: 0;
  text-align: left;
  font-size: 17px;
  font-weight: 800;
  overflow-wrap: anywhere;
}

.todo-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-top: 6px;
  color: #66727b;
  font-size: 13px;
}

.todo-meta strong {
  color: #1e6f5c;
}

.overdue .todo-meta strong {
  color: #b45309;
}

.todo-actions {
  display: flex;
  gap: 8px;
}

.habit-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 12px;
}

.habit-card {
  display: grid;
  gap: 14px;
  padding: 16px;
}

.habit-card.complete {
  border-color: #1e6f5c;
  background: #f3faf5;
}

.habit-card h2 {
  margin: 0;
  font-size: 18px;
}

.habit-card p {
  margin: 4px 0 0;
  color: #52636b;
}

.habit-progress {
  display: flex;
  align-items: baseline;
  gap: 4px;
}

.habit-progress strong {
  color: #1e6f5c;
  font-size: 36px;
  line-height: 1;
}

.habit-actions {
  display: grid;
  grid-template-columns: 44px 1fr auto;
  gap: 8px;
}

.ghost-action,
.danger-action {
  min-height: 36px;
  padding: 0 12px;
  font-weight: 800;
}

.ghost-action {
  background: #edf8f2;
  color: #1e6f5c;
}

.danger-action {
  background: #fff1f2;
  color: #be123c;
}

.empty {
  margin: 0;
  color: #52636b;
  line-height: 1.6;
}

@media (max-width: 760px) {
  .shell {
    width: min(100% - 24px, 1120px);
    padding: 24px 0;
  }

  h1 {
    font-size: 34px;
  }

  .summary {
    font-size: 16px;
  }

  .workspace {
    grid-template-columns: 1fr;
  }

  .todo-form,
  .todo-item {
    grid-template-columns: 1fr;
  }

  .todo-actions {
    justify-content: stretch;
  }

  .ghost-action,
  .danger-action,
  .primary-action {
    width: 100%;
  }
}
`;
  }

  private _readme(app: GeneratedApp): string {
    return `# ${this._specString(app.spec, 'name', 'DDD Generated App')}

${this._specString(app.spec, 'summary', 'Generated from ddd-spec.json.')}

## Run

Use the package manager available in your environment.

\`\`\`sh
npm install
npm run dev
\`\`\`

\`\`\`sh
pnpm install
pnpm dev
\`\`\`

\`\`\`sh
yarn install
yarn dev
\`\`\`

\`\`\`sh
bun install
bun run dev
\`\`\`
`;
  }

  private _specString(spec: Record<string, unknown>, key: string, fallback: string): string {
    const value = spec[key];
    return typeof value === 'string' && value.trim() ? value.trim() : fallback;
  }

  private _packageName(value: string): string {
    const name = value.toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '');
    return name || 'ddd-generated-app';
  }

  private _escapeHtml(value: string): string {
    return value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }
}
