import { execFile } from 'child_process';
import { createHash } from 'crypto';
import { promises as fs } from 'fs';
import * as path from 'path';
import { promisify } from 'util';
import { GeneratedApp, Decision } from '../models/types';

const execFileAsync = promisify(execFile);
const GIT_TIMEOUT_MS = 30_000;
const GH_TIMEOUT_MS = 30_000;

export interface PublishResult {
  repositoryUrl: string;
  branchName: string;
  pullRequestUrl: string;
}

export class GitHubPublisher {
  async publish(app: GeneratedApp, decisions: Decision[], repoPath: string): Promise<PublishResult> {
    const safeProjectId = this._safeToken(app.projectId);
    const branch = `ddd/${safeProjectId}`;
    const specPath = path.join(repoPath, 'ddd-spec.json');
    const decisionsPath = path.join(repoPath, 'ddd-decisions.json');
    const originalBranch = await this._currentBranch(repoPath);

    try {
      try {
        await execFileAsync('git', ['checkout', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      } catch {
        await execFileAsync('git', ['checkout', '-b', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      }

      // Write spec and decisions JSON
      await fs.writeFile(specPath, JSON.stringify(app.spec, null, 2));
      await fs.writeFile(decisionsPath, JSON.stringify(decisions, null, 2));

      await execFileAsync('git', ['add', specPath, decisionsPath], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      await execFileAsync('git', ['commit', '-m', 'chore: DDD generated app'], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
      await execFileAsync('git', ['push', '-u', 'origin', branch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });

      const titleName = typeof app.spec['name'] === 'string' ? app.spec['name'] : app.projectId;
      const { stdout } = await execFileAsync(
        'gh',
        [
          'pr',
          'create',
          '--title',
          `DDD: ${titleName}`,
          '--body',
          'Generated by Dopamine Driven Development',
          '--head',
          branch,
        ],
        { cwd: repoPath, timeout: GH_TIMEOUT_MS, shell: false },
      );
      const prUrl = stdout.trim();

      return {
        repositoryUrl: await this._repoUrl(repoPath),
        branchName: branch,
        pullRequestUrl: prUrl,
      };
    } catch (err) {
      console.error('DDD: GitHub publish failed', err);
      // GitHub step failed — return partial result so local state is preserved
      return { repositoryUrl: '', branchName: branch, pullRequestUrl: '' };
    } finally {
      if (originalBranch) {
        try {
          await execFileAsync('git', ['checkout', originalBranch], { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false });
        } catch (err) {
          console.error('DDD: Git branch restore failed', err);
        }
      }
    }
  }

  private async _currentBranch(repoPath: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync(
        'git',
        ['rev-parse', '--abbrev-ref', 'HEAD'],
        { cwd: repoPath, timeout: GIT_TIMEOUT_MS, shell: false },
      );
      return stdout.trim();
    } catch (err) {
      console.error('DDD: Git current branch lookup failed', err);
      return '';
    }
  }

  private async _repoUrl(repoPath: string): Promise<string> {
    try {
      const { stdout } = await execFileAsync(
        'gh',
        ['repo', 'view', '--json', 'url', '-q', '.url'],
        { cwd: repoPath, timeout: GH_TIMEOUT_MS, shell: false },
      );
      return stdout.trim();
    } catch (err) {
      console.error('DDD: GitHub repository URL lookup failed', err);
      return '';
    }
  }

  private _safeToken(value: string): string {
    const sanitized = value.replace(/[^A-Za-z0-9_-]/g, '-');
    if (sanitized.length > 0) {
      return sanitized;
    }

    const suffix = createHash('sha1').update(value).digest('hex').slice(0, 8);
    return `token-${suffix}`;
  }
}
