import './styles.css';
import appSpec from '../../ddd-spec.json';
import decisions from '../../ddd-decisions.json';

const asArray = (value) => Array.isArray(value) ? value : [];
const screens = asArray(appSpec.screens);
const features = asArray(appSpec.features);
const acceptedCount = decisions.filter((decision) => decision.action === 'accepted').length;
const rejectedCount = decisions.filter((decision) => decision.action === 'rejected').length;

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

document.querySelector('#app').innerHTML = `
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Generated by DDD</p>
      <h1>${escapeHtml(appSpec.name || 'Generated App')}</h1>
      <p class="summary">${escapeHtml(appSpec.summary || 'スワイプで選んだ仕様から作成されたアプリです。')}</p>
      <div class="metrics" aria-label="Decision summary">
        <span><strong>${acceptedCount}</strong> accepted</span>
        <span><strong>${rejectedCount}</strong> rejected</span>
        <span><strong>${features.length}</strong> features</span>
      </div>
    </section>

    <section class="workspace">
      <div class="panel primary">
        <div class="section-title">
          <span>Features</span>
          <small>${features.length} items</small>
        </div>
        <div class="feature-list">
          ${features.length > 0
            ? features.map((feature, index) => `
              <button class="feature" type="button">
                <span class="feature-index">${index + 1}</span>
                <span>${escapeHtml(String(feature))}</span>
              </button>
            `).join('')
            : '<p class="empty">採用された機能がまだありません。</p>'}
        </div>
      </div>

      <div class="panel">
        <div class="section-title">
          <span>Screens</span>
          <small>${screens.length} views</small>
        </div>
        <div class="screen-list">
          ${screens.length > 0
            ? screens.map((screen) => `
              <article class="screen">
                <h2>${escapeHtml(screen?.name || 'Screen')}</h2>
                <p>${escapeHtml(screen?.description || '')}</p>
              </article>
            `).join('')
            : '<p class="empty">画面仕様がまだありません。</p>'}
        </div>
      </div>
    </section>
  </main>
`;
